src/Entity/Forecast.php
<?php

namespace App\Entity;

use App\Repository\ForecastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ForecastRepository::class)]
class Forecast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'forecasts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $time = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $temperature = null;

    #[ORM\Column(length: 2)]
    private ?string $wind_direction = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $wind_speed = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $rain = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): static
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getWindDirection(): ?string
    {
        return $this->wind_direction;
    }

    public function setWindDirection(string $wind_direction): static
    {
        $this->wind_direction = $wind_direction;

        return $this;
    }

    public function getWindSpeed(): ?string
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(string $wind_speed): static
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getRain(): ?string
    {
        return $this->rain;
    }

    public function setRain(string $rain): static
    {
        $this->rain = $rain;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ForecastType.php
<?php

namespace App\Form;

use App\Entity\Forecast;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ForecastType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('time', DateType::class, [
                'widget' => 'single_text',
                'html5' => true,
            ])
            ->add('temperature', NumberType::class, [
                'html5' => true,

            ])
            ->add('wind_direction', ChoiceType::class, [
                'choices' => [
                    'NN' => 'NN',
                    'NE' => 'NE',
                    'NW' => 'NW',
                    'WW' => 'WW',
                    'WS' => 'WS',
                    'WN' => 'WN',
                    'SS' => 'SS',
                    'SE' => 'SE',
                    'SW' => 'SW',
                    'EE' => 'EE',
                    'EN' => 'EN',
                    'ES' => 'ES',

                ],
            ])
            ->add('wind_speed', NumberType::class, [
                'html5' => true,
        
            ])

            ->add('rain', NumberType::class, [
                'html5' => true,
        
            ])
            ->add('location', EntityType::class, [
                'class' => 'App\Entity\Location',
                'choice_label' => 'city',
            ])

            ->add('description', null, [
                'attr' => [
                    'placeholder' => 'Enter description',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Forecast::class,
        ]);
    }
}

src/Controller/ForecastController.php
<?php

namespace App\Controller;

use App\Entity\Forecast;
use App\Form\ForecastType;
use App\Repository\ForecastRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/forecast')]
class ForecastController extends AbstractController
{
    #[Route('/', name: 'app_forecast_index', methods: ['GET'])]
    #[IsGranted('ROLE_FORECAST_INDEX')]
    public function index(ForecastRepository $forecastRepository): Response
    {
        return $this->render('forecast/index.html.twig', [
            'forecasts' => $forecastRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_forecast_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORECAST_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $forecast = new Forecast();
        $form = $this->createForm(ForecastType::class, $forecast, [
            'validation_groups' => 'create',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($forecast);
            $entityManager->flush();

            return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forecast/new.html.twig', [
            'forecast' => $forecast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forecast_show', methods: ['GET'])]
    #[IsGranted('ROLE_FORECAST_SHOW')]
    public function show(Forecast $forecast): Response
    {
        return $this->render('forecast/show.html.twig', [
            'forecast' => $forecast,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_forecast_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORECAST_EDIT')]
    public function edit(Request $request, Forecast $forecast, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ForecastType::class, $forecast, [
            'validation_groups' => 'edit',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forecast/edit.html.twig', [
            'forecast' => $forecast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forecast_delete', methods: ['POST'])]
    #[IsGranted('ROLE_FORECAST_DELETE')]
    public function delete(Request $request, Forecast $forecast, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$forecast->getId(), $request->request->get('_token'))) {
            $entityManager->remove($forecast);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/forecast/_delete_form.html.twig
<form method="post" action="{{ path('app_forecast_delete', {'id': forecast.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ forecast.id) }}">
    <button class="btn">Delete</button>
</form>

templates/forecast/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/forecast/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Forecast{% endblock %}

{% block body %}
    <h1>Edit Forecast</h1>

    {{ include('forecast/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_forecast_index') }}">back to list</a>

    {{ include('forecast/_delete_form.html.twig') }}
{% endblock %}

templates/forecast/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forecast index{% endblock %}

{% block body %}
    <h1>Forecast index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Time</th>
                <th>Temperature</th>
                <th>Wind_direction</th>
                <th>Wind_speed</th>
                <th>Rain</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for forecast in forecasts %}
            <tr>
                <td>{{ forecast.id }}</td>
                <td>{{ forecast.time ? forecast.time|date('Y-m-d') : '' }}</td>
                <td>{{ forecast.temperature }}</td>
                <td>{{ forecast.windDirection }}</td>
                <td>{{ forecast.windSpeed }}</td>
                <td>{{ forecast.rain }}</td>
                <td>{{ forecast.description }}</td>
                <td>
                    {% if is_granted('ROLE_FORECAST_SHOW') %}
                        <a href="{{ path('app_forecast_show', {'id': forecast.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_FORECAST_EDIT') %}
                        <a href="{{ path('app_forecast_edit', {'id': forecast.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_FORECAST_NEW') %}
        <a href="{{ path('app_forecast_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/forecast/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Forecast{% endblock %}

{% block body %}
    <h1>Create new Forecast</h1>

    {{ include('forecast/_form.html.twig') }}

    <a href="{{ path('app_forecast_index') }}">back to list</a>
{% endblock %}

templates/forecast/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forecast{% endblock %}

{% block body %}
    <h1>Forecast</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ forecast.id }}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td>{{ forecast.time ? forecast.time|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ forecast.temperature }}</td>
            </tr>
            <tr>
                <th>Wind_direction</th>
                <td>{{ forecast.windDirection }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ forecast.windSpeed }}</td>
            </tr>
            <tr>
                <th>Rain</th>
                <td>{{ forecast.rain }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ forecast.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_forecast_index') }}">back to list</a>

    <a href="{{ path('app_forecast_edit', {'id': forecast.id}) }}">edit</a>

    {{ include('forecast/_delete_form.html.twig') }}
{% endblock %}